# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.setWindowModality(QtCore.Qt.ApplicationModal)
        About.resize(682, 465)
        About.setMinimumSize(QtCore.QSize(682, 465))
        About.setMaximumSize(QtCore.QSize(682, 465))
        About.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/req/Create a new project/Yun.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        About.setWindowIcon(icon)
        self.copyright = QtWidgets.QLabel(About)
        self.copyright.setGeometry(QtCore.QRect(302, 390, 141, 63))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.copyright.setFont(font)
        self.copyright.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.copyright.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.copyright.setObjectName("copyright")
        self.logogo = QtWidgets.QPushButton(About)
        self.logogo.setGeometry(QtCore.QRect(450, 385, 172, 66))
        self.logogo.setText("")
        self.logogo.setFlat(True)
        self.logogo.setObjectName("logogo")
        self.label_3 = QtWidgets.QLabel(About)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 641, 441))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.aboutus = QtWidgets.QLabel(About)
        self.aboutus.setGeometry(QtCore.QRect(70, 20, 151, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.aboutus.setFont(font)
        self.aboutus.setObjectName("aboutus")
        self.text = QtWidgets.QTextBrowser(About)
        self.text.setGeometry(QtCore.QRect(50, 70, 581, 322))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.label_3.raise_()
        self.logogo.raise_()
        self.copyright.raise_()
        self.aboutus.raise_()
        self.text.raise_()

        self.retranslateUi(About)
        self.logogo.clicked.connect(About.openweb)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.copyright.setText(_translate("About", "Copyright(c) by"))
        self.aboutus.setText(_translate("About", "关于我们"))
        self.text.setHtml(_translate("About", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">    合肥云联半导体有限公司成立于2020年6月，是一家专注于研发音视频的传输，发送，接收，编解码以及接口等处理芯片和高性能低功耗无线物联网系统级芯片的设计公司。公司总部位于合肥市高新区创新产业园，在北京，深圳和上海设有办事处。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">    公司主营业务为集成电路IC设计研发和销售，并可以实现定制化芯片设计、单芯片解决方案以及SOC芯片解决方案，同时提供相关技术咨询和技术服务。目前公司主要产品包括VT8系列低功耗4K超高清端口处理芯片，VT2202S低功耗HDMI2.0中继芯片，VT5101M/VT5101H低功耗4K超高清转换芯片（HDMI2.0,MIPI系列）以及VTC05系列低功耗蓝牙5.1/5.0SOC芯片，应用的行业有专业音视频，广电系统，车载音视频，医疗显示类产品，以及蓝牙室内定位，蓝牙低功耗组网，蓝牙智慧场景等物联网领域。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">云联半导体拥有设计能力和设计经验丰富的团队，核心成员具有多年ASIC/SOC芯片开发经验，熟悉模拟、数字和后端技术，精通设计、仿真以及流片、封装、测试全流程，在接口性IP、CPU、显示驱动、图形、音频处理，无线通讯技术等领域均有深厚的技术积累。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">    公司秉承“持续创新，精工细作，分享共赢”的理念，始终向客户提供高性能高品质的芯片，帮助客户快速推出新产品，并建立长期稳定的合作关系。</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\';\"><br /></p></body></html>"))
import req_rc
