# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importpath.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add(object):
    def setupUi(self, add):
        add.setObjectName("add")
        add.setWindowModality(QtCore.Qt.ApplicationModal)
        add.resize(654, 465)
        add.setMinimumSize(QtCore.QSize(654, 465))
        add.setMaximumSize(QtCore.QSize(654, 465))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        add.setFont(font)
        add.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/req/Create a new project/Yun.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        add.setWindowIcon(icon)
        self.pushButton_2 = QtWidgets.QPushButton(add)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 240, 30, 32))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("border-image: url(:/新前缀/update/画板 – 3_slices/文件 (1).png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.projectPath = QtWidgets.QLineEdit(add)
        self.projectPath.setGeometry(QtCore.QRect(52, 245, 485, 26))
        self.projectPath.setText("")
        self.projectPath.setObjectName("projectPath")
        self.label_2 = QtWidgets.QLabel(add)
        self.label_2.setGeometry(QtCore.QRect(52, 217, 451, 16))
        self.label_2.setObjectName("label_2")
        self.projectTrue = QtWidgets.QPushButton(add)
        self.projectTrue.setEnabled(False)
        self.projectTrue.setGeometry(QtCore.QRect(580, 240, 31, 31))
        self.projectTrue.setStyleSheet("border-image: url(:/req/YunWizard-v5.7.0/true.png);")
        self.projectTrue.setText("")
        self.projectTrue.setObjectName("projectTrue")
        self.projectName = QtWidgets.QLineEdit(add)
        self.projectName.setGeometry(QtCore.QRect(52, 140, 485, 26))
        self.projectName.setObjectName("projectName")
        self.label_3 = QtWidgets.QLabel(add)
        self.label_3.setGeometry(QtCore.QRect(52, 110, 451, 16))
        self.label_3.setObjectName("label_3")
        self.pushButton_4 = QtWidgets.QPushButton(add)
        self.pushButton_4.setGeometry(QtCore.QRect(12, 393, 93, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/新前缀/update/画板 – 4_slices/叉叉.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(add)
        self.pushButton_3.setGeometry(QtCore.QRect(553, 393, 93, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/新前缀/update/画板 – 4_slices/对号-加粗.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(add)
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QtCore.QRect(453, 393, 91, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.pushButton_7.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/req/update/画板 – 4_slices/下一步_slices/下一步.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.projectFalse = QtWidgets.QPushButton(add)
        self.projectFalse.setEnabled(False)
        self.projectFalse.setGeometry(QtCore.QRect(590, 250, 20, 20))
        self.projectFalse.setStyleSheet("border-image: url(:/新前缀/update/画板 – 3_slices/叉叉.png);")
        self.projectFalse.setText("")
        self.projectFalse.setObjectName("projectFalse")

        self.retranslateUi(add)
        self.pushButton_4.clicked.connect(add.close)
        self.pushButton_3.clicked.connect(add.add)
        self.pushButton_2.clicked.connect(add.openfile)
        self.pushButton_7.clicked.connect(add.back)
        QtCore.QMetaObject.connectSlotsByName(add)

    def retranslateUi(self, add):
        _translate = QtCore.QCoreApplication.translate
        add.setWindowTitle(_translate("add", "Import Project"))
        self.label_2.setText(_translate("add", "*.uvprojx executable location (e.g. C:\\Project.uvprojx)"))
        self.projectName.setText(_translate("add", "Test_Project"))
        self.label_3.setText(_translate("add", "Project Name"))
        self.pushButton_4.setText(_translate("add", "Cancel"))
        self.pushButton_3.setText(_translate("add", "Import"))
        self.pushButton_7.setText(_translate("add", "Back"))
import req_rc
